### PR TITLE
change var dump to dump (1.7+)

### PR DESCRIPTION
**Pull request by jf-viguier**
Thanks for your work.
It seems 1.6 oriented ?

### CODE REVIEW

**Comment by jf-viguier** [comment]
any news here ?

**Comment by jf-viguier** [comment]
Is this project still alive ?

**Comment by MatviyRoman** [comment]
Hi, yes.

**Comment by MatviyRoman** [comment]
Hi. I have added your changes. Thank you for your contribution to this project.

**Pull request merged**
